# Generated by Django 5.2 on 2025-07-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userbankaccount_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='last_loan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='loan_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
