# Generated by Django 5.2 on 2025-07-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'Loan Request',
                'verbose_name_plural': 'Loan Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactions.transaction',),
        ),
    ]
