# Generated by Django 5.2 on 2025-07-05 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_loantransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='original_loan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='transactions.transaction'),
        ),
    ]
