# Generated by Django 5.2 on 2025-07-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_original_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='original_loan',
        ),
    ]
