# Generated by Django 5.2 on 2025-07-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userbankaccount_account_type_and_more'),
        ('transactions', '0005_remove_transaction_original_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='loan_approve',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'transaction_type'], name='transaction_account_6aecfc_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='transaction_transac_09d7ec_idx'),
        ),
    ]
