# Generated by Django 5.2 on 2025-07-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userbankaccount_last_loan_date_and_more'),
        ('transactions', '0006_alter_transaction_loan_approve_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['timestamp'], name='transaction_timesta_20dac7_idx'),
        ),
    ]
