# Generated by Django 5.2 on 2025-08-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_transaction_timesta_20dac7_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance_after_transaction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='loan_approve',
            field=models.BooleanField(default=False),
        ),
    ]
